# Brain Tumor Detection
## Resnet101 - Classifier + Regressor
Description
This dataset was originally created by Yousef Ghanem. To see the current project, which may have been updated since this version, please go here: https://universe.roboflow.com/yousef-ghanem-jzj4y/brain-tumor-detection-fpf1f.

This dataset is part of RF100, an Intel-sponsored initiative to create a new object detection benchmark for model generalizability.

Access the RF100 Github repo: https://github.com/roboflow-ai/roboflow-100-benchmark

## Imports

In [1]:
# Go to project root folder
import os
os.chdir("../")
%pwd

'/workspaces/brain-tumor-detection'

In [2]:
import numpy as np
from pathlib import Path
from dotenv import load_dotenv
load_dotenv()

import tensorflow as tf
tf.random.set_seed(42)

import matplotlib.pyplot as plt

2025-03-23 15:09:08.915424: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1742742548.924150   34664 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1742742548.926983   34664 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1742742548.937222   34664 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1742742548.937242   34664 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1742742548.937244   34664 computation_placer.cc:177] computation placer alr

In [3]:
found_gpu = tf.config.list_physical_devices('GPU')
if not found_gpu:
    raise Exception("No GPU found")
found_gpu, tf.__version__

([PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')], '2.19.0')

In [4]:
from src.data_handler.data_loader import DataLoader
from src.data_handler.annotation_processor import AnnotationProcessor
from src.data_handler.preprocessor import Preprocessor

In [5]:
# auto reload dotenv 
%load_ext dotenv
%dotenv

# auto reload libs
%load_ext autoreload
%autoreload 2

## Paths Setup

In [6]:
from hydra import initialize, compose

# https://gist.github.com/bdsaglam/586704a98336a0cf0a65a6e7c247d248

with initialize(version_base=None, config_path="../conf"):
    cfg = compose(config_name="config")
    print(cfg.DATASET_DIRS.TRAIN_DIR)

datasets/-Brain-Tumor-Detection-2/train/


In [7]:
cfg.DATASET_DIRS

{'TRAIN_DIR': '${DATASET.DATASET_DIR}/${DATASET.DATASET_NAME}/train/', 'VALIDATION_DIR': '${DATASET.DATASET_DIR}/${DATASET.DATASET_NAME}/valid', 'TEST_DIR': '${DATASET.DATASET_DIR}/${DATASET.DATASET_NAME}/test'}

In [8]:
DATASET_DIRS = Path(cfg.DATASET.DATASET_DIR)
TRAIN_DIR = Path(cfg.DATASET_DIRS.TRAIN_DIR)
VALIDATION_DIR = Path(cfg.DATASET_DIRS.VALIDATION_DIR)
TEST_DIR = Path(cfg.DATASET_DIRS.TEST_DIR)
OUTPUT_DIR = Path(cfg.OUTPUTS.OUTPUT_DIR)

IMG_SIZE = cfg.TRAIN.IMG_SIZE
BATCH_SIZE = cfg.TRAIN.BATCH_SIZE
LOG_DIR = cfg.OUTPUTS.LOG_DIR
CHECK_POINT_DIR = Path(cfg.OUTPUTS.CHECKPOINT_PATH)
CLASS_NAME = [
    'label0',
    'label1',
    'label2'
]
class_map = {k: v for k, v in enumerate(CLASS_NAME)}

NUM_EPOCHS = cfg.TRAIN.NUM_EPOCHS
LEARNING_RATE = cfg.TRAIN.LEARNING_RATE

NUM_CLASSES = len(CLASS_NAME)

## Dataset Download from Roboflow

In [9]:
if not TRAIN_DIR.exists():
    from roboflow import Roboflow
    rf = Roboflow()
    project = rf.workspace("yousef-ghanem-jzj4y").project("brain-tumor-detection-fpf1f")
    version = project.version(2)
    dataset = version.download("tensorflow") 

## Load images from directory

In [10]:
prepare_train_dataset = AnnotationProcessor(annotation_file= str(TRAIN_DIR/'_annotations.csv'))
_class_map = {v: k for k, v in enumerate(CLASS_NAME)}
train_images, train_class_ids, train_bboxes  = prepare_train_dataset.process_annotations(image_dir=TRAIN_DIR, class_id_map=_class_map)

len(train_images), len(train_class_ids), len(train_bboxes)

(6851, 6851, 6851)

In [11]:
train_bboxes[0]

array([[0.68345324, 0.54545455, 0.95683453, 0.76515152],
       [0.42446043, 0.48484848, 0.99280576, 0.96969697],
       [0.46043165, 0.53030303, 0.99280576, 0.78030303]])

In [12]:
train_class_ids

[[0, 1, 2],
 [0, 1, 2],
 [0, 1, 2],
 [0, 1, 2],
 [1],
 [0, 1, 2],
 [0, 1, 2],
 [0, 1],
 [0, 1, 2],
 [0, 1, 2],
 [1, 2],
 [0, 1],
 [1],
 [1],
 [0, 1, 2],
 [0, 1, 2],
 [1],
 [0, 1, 2],
 [0, 1, 2],
 [0, 1, 2],
 [0, 1, 2],
 [0, 1, 2],
 [1],
 [1, 2],
 [0, 1],
 [2],
 [1],
 [0, 1, 2],
 [1],
 [1],
 [1],
 [0, 1, 2],
 [0, 1, 2],
 [1],
 [0, 1, 2],
 [1, 2],
 [1],
 [0, 1, 2],
 [0, 1, 2],
 [1],
 [0, 1],
 [1, 2],
 [0, 1, 2],
 [0, 1, 2],
 [0, 1, 2],
 [1],
 [0, 1, 2],
 [1],
 [0, 1, 2],
 [0, 1, 2],
 [0, 1, 2],
 [0, 1, 2],
 [1, 2],
 [1],
 [0, 1, 2],
 [0, 1, 2],
 [0, 1, 2],
 [0, 1, 2],
 [0, 1, 2],
 [0, 1, 2],
 [0, 1, 2],
 [1, 2],
 [0, 1, 2],
 [0, 1, 2],
 [0, 1, 2],
 [0, 1, 2],
 [0, 1],
 [0, 1, 2],
 [1],
 [0, 1],
 [0, 1, 2],
 [1],
 [1, 2],
 [0, 1, 2],
 [0, 1, 2],
 [0, 1, 2],
 [1],
 [1, 2],
 [1],
 [0, 1, 2],
 [0, 1, 2],
 [0, 1, 2],
 [0, 1, 2],
 [1],
 [0, 1, 2],
 [0, 1, 2],
 [1],
 [1],
 [1],
 [0, 1, 2],
 [0, 1, 2],
 [1],
 [0, 1, 2],
 [0, 1, 2],
 [0, 1, 2],
 [0, 1, 2],
 [1],
 [0, 1, 2],
 [0, 1, 2],
 [0, 1, 2]

In [13]:
train_dl = DataLoader(train_images, train_class_ids, train_bboxes)
train_ds = train_dl.load_train_dataset()
train_ds = Preprocessor(train_ds).preprocess()
train_ds = train_ds.batch(BATCH_SIZE)\
                .prefetch(tf.data.AUTOTUNE)

I0000 00:00:1742742562.771904   34664 gpu_device.cc:2019] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 7147 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3080, pci bus id: 0000:0a:00.0, compute capability: 8.6


In [14]:
for batch in train_ds.take(1):
    image, (cls, bbx) = batch
    print(image.shape, cls.shape, bbx.shape)
    print(cls[5])
    print(image[1].numpy().min(), image[1].numpy().max())
    for c in cls:
        print(c.numpy())

(64, 240, 240, 3) (64, 3) (64, 3, 4)
tf.Tensor([1. 1. 1.], shape=(3,), dtype=float32)
-89.58537 151.061
[0. 1. 0.]
[0. 1. 0.]
[1. 1. 1.]
[1. 1. 1.]
[0. 1. 0.]
[1. 1. 1.]
[1. 1. 0.]
[1. 1. 1.]
[0. 1. 0.]
[1. 1. 1.]
[1. 1. 1.]
[1. 1. 1.]
[1. 1. 1.]
[0. 1. 0.]
[1. 1. 1.]
[1. 1. 1.]
[1. 1. 0.]
[0. 1. 0.]
[1. 1. 1.]
[0. 1. 0.]
[0. 1. 0.]
[1. 1. 1.]
[0. 1. 0.]
[1. 1. 1.]
[1. 1. 0.]
[0. 1. 0.]
[1. 1. 1.]
[1. 1. 1.]
[0. 1. 0.]
[1. 1. 1.]
[1. 1. 1.]
[0. 1. 0.]
[1. 1. 1.]
[1. 1. 1.]
[1. 1. 1.]
[0. 1. 1.]
[0. 1. 0.]
[0. 1. 0.]
[1. 1. 1.]
[1. 1. 1.]
[0. 1. 1.]
[1. 1. 1.]
[0. 1. 0.]
[1. 1. 1.]
[0. 1. 0.]
[1. 1. 1.]
[1. 1. 1.]
[0. 1. 0.]
[0. 1. 0.]
[1. 1. 1.]
[0. 1. 0.]
[0. 1. 0.]
[1. 1. 1.]
[1. 1. 1.]
[1. 1. 1.]
[1. 1. 1.]
[0. 1. 0.]
[1. 0. 0.]
[1. 1. 1.]
[1. 1. 0.]
[1. 1. 1.]
[1. 1. 1.]
[0. 1. 0.]
[1. 1. 1.]


2025-03-23 15:09:29.036919: I tensorflow/core/framework/local_rendezvous.cc:407] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


### Validation datasets setup

In [15]:
prepare_valid_dataset = AnnotationProcessor(annotation_file= str(VALIDATION_DIR/'_annotations.csv'))

valid_image_paths, valid_class_ids, valid_bboxes  = prepare_valid_dataset.process_annotations(image_dir=VALIDATION_DIR, class_id_map=_class_map)
len(valid_image_paths), len(valid_class_ids), len(valid_bboxes)

(1963, 1963, 1963)

In [16]:
valid_dl = DataLoader(valid_image_paths, valid_class_ids, valid_bboxes).load_val_dataset()
valid_ds = Preprocessor(valid_dl).preprocess()
valid_ds = valid_ds.batch(BATCH_SIZE)\
                .prefetch(tf.data.AUTOTUNE)

In [17]:
for batch in valid_ds.take(1):
    image, (cls, bbx) = batch
    print(image.shape, cls.shape, bbx.shape)
    print(image[1].numpy().min(), image[1].numpy().max())

(64, 240, 240, 3) (64, 3) (64, 3, 4)
-123.68 138.49847


2025-03-23 15:09:30.600142: I tensorflow/core/framework/local_rendezvous.cc:407] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


## Training Setup

## Define loss

In [18]:
padded_class_ids = train_dl.multi_hot_class_ids
padded_class_ids[:10]

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 1., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 0.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [19]:
from src.losses import binary_weighted_loss as _loss

positive_weights, negative_weights = _loss.compute_class_weights(padded_class_ids)
positive_weights, negative_weights 

(array([0.38140417, 0.01547219, 0.40767771]),
 array([0.61859584, 0.9845278 , 0.5923223 ], dtype=float32))

## Define ResNet50 Model

### Final Model

In [20]:
from src.losses import iou_loss
CLS_METRICS = [
    tf.keras.metrics.AUC(name='AUC', multi_label=True), 
    tf.keras.metrics.F1Score(name='f1_score',average='weighted')]


REG_METRICS = [
    iou_loss.iou_metric,
    tf.keras.metrics.MeanSquaredError(name='mse'),
    tf.keras.metrics.MeanAbsoluteError(name='mae'),]

### Define  Callbacks

In [21]:
from mlflow.models.signature import ModelSignature
from mlflow.types.schema import Schema, TensorSpec
# 1. Input Schema
# -----------------
# Your input is a batch of images with shape (32, 240, 240, 3)
# We use -1 to indicate that the batch size can vary.
input_schema = Schema([TensorSpec(np.dtype(np.float32), (-1, IMG_SIZE, IMG_SIZE, 3), "image")])

# 2. Output Schema - Multilabel binary classification head
# ------------------
# Your model outputs a list of two arrays. We need to define a schema for each.
# Array 1: Shape (1, 3)
output_schema_array1 = TensorSpec(np.dtype(np.float32), (-1, 3), "classification")

# Array 2: Shape (1, 3, 4) - 3 Bounding boxes per classification 
output_schema_array2 = TensorSpec(np.dtype(np.float32), (-1, 3, 4), "bounding_box")

# Create a schema for the list of outputs
output_schema = Schema([output_schema_array1, output_schema_array2])

# 3. Model Signature
# --------------------
# Combine the input and output schemas into a ModelSignature
signature = ModelSignature(inputs=input_schema, outputs=output_schema)

In [22]:
import os
import mlflow
# to_monitor = 'val_classification_AUC'
# mode = 'max'
to_monitor = 'val_bounding_box_mse'
mode = 'min'
callbacks = [
    tf.keras.callbacks.ReduceLROnPlateau(factor=0.1, 
                                            patience=5, 
                                            monitor=to_monitor,
                                            mode=mode,
                                            min_lr=1e-7,
                                            verbose=1),

    tf.keras.callbacks.ModelCheckpoint(filepath=os.path.join(str(CHECK_POINT_DIR), "detector_ckpt_{epoch}.keras") ,
                                        save_weights_only=False,
                                        save_best_only=True,
                                        monitor=to_monitor,
                                        mode=mode,
                                        verbose=1),
                                        
    tf.keras.callbacks.EarlyStopping(monitor=to_monitor, 
                                    patience=10,
                                    mode=mode, 
                                    restore_best_weights=True,
                                    verbose=1),

    ]

mlflow_exp = mlflow.set_experiment("/brain-tumor-resnet101-detector")

### Define Optimizer

In [23]:
optimizer=tf.keras.optimizers.AdamW()

## Model Building and Compilation

In [24]:
from src.models.resnet101V2 import final_model
tf.keras.backend.clear_session()

model = final_model(input_shape=(IMG_SIZE, IMG_SIZE, 3), num_classes=NUM_CLASSES)

model.compile(
    optimizer=optimizer,
    loss={'classification': _loss.set_binary_crossentropy_weighted_loss(positive_weights, negative_weights),
          'bounding_box': 'mse'},
        #   'bounding_box': iou_loss.iou_loss},
    metrics={'classification': CLS_METRICS, 'bounding_box': REG_METRICS},
    # Train with 0 weight for classification
    loss_weights={
                'classification': 0,  # Example: Reduce weight for classification
                'bounding_box': 1    # Example: Increase weight for regression
            },
    )

model.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer         │ (None, 240, 240,  │          0 │ -                 │
│ (InputLayer)        │ 3)                │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv1_pad           │ (None, 246, 246,  │          0 │ input_layer[0][0] │
│ (ZeroPadding2D)     │ 3)                │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv1_conv (Conv2D) │ (None, 120, 120,  │      9,472 │ conv1_pad[0][0]   │
│                     │ 64)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ pool1_pad           │ (None, 122, 122,  │          0 │ conv1_conv[0][0]  │
│ (ZeroPadding2D)     │ 64)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ pool1_pool          │ (None, 60, 60,    │          0 │ pool1_pad[0][0]   │
│ (MaxPooling2D)      │ 64)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2_block1_preac… │ (None, 60, 60,    │        256 │ pool1_pool[0][0]  │
│ (BatchNormalizatio… │ 64)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2_block1_preac… │ (None, 60, 60,    │          0 │ conv2_block1_pre… │
│ (Activation)        │ 64)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2_block1_1_conv │ (None, 60, 60,    │      4,096 │ conv2_block1_pre… │
│ (Conv2D)            │ 64)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2_block1_1_bn   │ (None, 60, 60,    │        256 │ conv2_block1_1_c… │
│ (BatchNormalizatio… │ 64)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2_block1_1_relu │ (None, 60, 60,    │          0 │ conv2_block1_1_b… │
│ (Activation)        │ 64)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2_block1_2_pad  │ (None, 62, 62,    │          0 │ conv2_block1_1_r… │
│ (ZeroPadding2D)     │ 64)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2_block1_2_conv │ (None, 60, 60,    │     36,864 │ conv2_block1_2_p… │
│ (Conv2D)            │ 64)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2_block1_2_bn   │ (None, 60, 60,    │        256 │ conv2_block1_2_c… │
│ (BatchNormalizatio… │ 64)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2_block1_2_relu │ (None, 60, 60,    │          0 │ conv2_block1_2_b… │
│ (Activation)        │ 64)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2_block1_0_conv │ (None, 60, 60,    │     16,640 │ conv2_block1_pre… │
│ (Conv2D)            │ 256)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2_block1_3_conv │ (None, 60, 60,    │     16,640 │ conv2_block1_2_r… │
│ (Conv2D)            │ 256)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2_block1_out    │ (None, 60, 60,    │          0 │ conv2_block1_0_c

 Total params: 57,841,935 (220.65 MB)

 Trainable params: 23,095,055 (88.10 MB)

 Non-trainable params: 34,746,880 (132.55 MB)

### Train and Validate the model

### Only train localization/Regressor head

In [25]:
with mlflow.start_run() as run:
    mlflow.tensorflow.autolog(log_models=True, 
                            log_datasets=False, 
                            log_input_examples=True,
                            log_model_signatures=True,
                            keras_model_kwargs={"save_format": "keras"},
                            checkpoint_monitor=to_monitor, 
                            checkpoint_mode=mode)
    history = model.fit(
        train_ds,
        epochs=30,
        validation_data=valid_ds,
        batch_size=BATCH_SIZE,
        callbacks=[callbacks])
    
    
    mlflow.tensorflow.log_model(
    model,
    "my_model",
    signature=signature,
    code_paths=["src/losses"])

2025/03/23 15:09:36 WARNING mlflow.utils.autologging_utils: MLflow tensorflow autologging is known to be compatible with 2.7.4 <= tensorflow <= 2.18.0, but the installed version is 2.19.0. If you encounter errors during autologging, try upgrading / downgrading tensorflow to a compatible version, or try upgrading MLflow.


Epoch 1/30


I0000 00:00:1742742590.803678   34911 service.cc:152] XLA service 0x721d3c0020e0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
I0000 00:00:1742742590.803745   34911 service.cc:160]   StreamExecutor device (0): NVIDIA GeForce RTX 3080, Compute Capability 8.6
2025-03-23 15:09:51.228480: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:269] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
I0000 00:00:1742742592.977933   34911 cuda_dnn.cc:529] Loaded cuDNN version 90300


  1/108 ━━━━━━━━━━━━━━━━━━━━ 46:59 26s/step - bounding_box_iou_metric: 7.1992e-04 - bounding_box_loss: 0.4828 - bounding_box_mae: 0.5401 - bounding_box_mse: 0.4828 - classification_AUC: 0.4024 - classification_f1_score: 0.4652 - classification_loss: 0.6878 - loss: 0.5442

I0000 00:00:1742742602.487112   34911 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.


108/108 ━━━━━━━━━━━━━━━━━━━━ 0s 173ms/step - bounding_box_iou_metric: 0.0190 - bounding_box_loss: 22.0522 - bounding_box_mae: 0.9198 - bounding_box_mse: 22.0527 - classification_AUC: 0.5126 - classification_f1_score: 0.3942 - classification_loss: 0.6842 - loss: 22.0805
Epoch 1: val_bounding_box_mse improved from inf to 0.08020, saving model to output/checkpoints/detector_ckpt_1.keras


108/108 ━━━━━━━━━━━━━━━━━━━━ 61s 324ms/step - bounding_box_iou_metric: 0.0192 - bounding_box_loss: 21.8981 - bounding_box_mae: 0.9152 - bounding_box_mse: 21.8989 - classification_AUC: 0.5127 - classification_f1_score: 0.3939 - classification_loss: 0.6842 - loss: 21.9266 - val_bounding_box_iou_metric: 0.0343 - val_bounding_box_loss: 0.0802 - val_bounding_box_mae: 0.2418 - val_bounding_box_mse: 0.0802 - val_classification_AUC: 0.4887 - val_classification_f1_score: 0.4364 - val_classification_loss: 0.6748 - val_loss: 0.0803 - learning_rate: 0.0010
Epoch 2/30
107/108 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - bounding_box_iou_metric: 0.0488 - bounding_box_loss: 0.0817 - bounding_box_mae: 0.2424 - bounding_box_mse: 0.0817 - classification_AUC: 0.5007 - classification_f1_score: 0.2876 - classification_loss: 0.6856 - loss: 0.0817
Epoch 2: val_bounding_box_mse improved from 0.08020 to 0.07890, saving model to output/checkpoints/detector_ckpt_2.keras


108/108 ━━━━━━━━━━━━━━━━━━━━ 23s 166ms/step - bounding_box_iou_metric: 0.0489 - bounding_box_loss: 0.0816 - bounding_box_mae: 0.2424 - bounding_box_mse: 0.0816 - classification_AUC: 0.5008 - classification_f1_score: 0.2881 - classification_loss: 0.6855 - loss: 0.0817 - val_bounding_box_iou_metric: 0.0539 - val_bounding_box_loss: 0.0788 - val_bounding_box_mae: 0.2383 - val_bounding_box_mse: 0.0789 - val_classification_AUC: 0.5000 - val_classification_f1_score: 0.3352 - val_classification_loss: 0.6745 - val_loss: 0.0789 - learning_rate: 0.0010
Epoch 3/30
107/108 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step - bounding_box_iou_metric: 0.0649 - bounding_box_loss: 0.0776 - bounding_box_mae: 0.2336 - bounding_box_mse: 0.0776 - classification_AUC: 0.5000 - classification_f1_score: 0.4510 - classification_loss: 0.6812 - loss: 0.0776
Epoch 3: val_bounding_box_mse improved from 0.07890 to 0.07653, saving model to output/checkpoints/detector_ckpt_3.keras


108/108 ━━━━━━━━━━━━━━━━━━━━ 22s 158ms/step - bounding_box_iou_metric: 0.0649 - bounding_box_loss: 0.0776 - bounding_box_mae: 0.2335 - bounding_box_mse: 0.0776 - classification_AUC: 0.5000 - classification_f1_score: 0.4532 - classification_loss: 0.6812 - loss: 0.0776 - val_bounding_box_iou_metric: 0.0428 - val_bounding_box_loss: 0.0765 - val_bounding_box_mae: 0.2346 - val_bounding_box_mse: 0.0765 - val_classification_AUC: 0.5000 - val_classification_f1_score: 0.6962 - val_classification_loss: 0.6745 - val_loss: 0.0765 - learning_rate: 0.0010
Epoch 4/30
107/108 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step - bounding_box_iou_metric: 0.0697 - bounding_box_loss: 0.0746 - bounding_box_mae: 0.2282 - bounding_box_mse: 0.0746 - classification_AUC: 0.5000 - classification_f1_score: 0.7528 - classification_loss: 0.6839 - loss: 0.0746
Epoch 4: val_bounding_box_mse improved from 0.07653 to 0.07432, saving model to output/checkpoints/detector_ckpt_4.keras


108/108 ━━━━━━━━━━━━━━━━━━━━ 23s 172ms/step - bounding_box_iou_metric: 0.0698 - bounding_box_loss: 0.0746 - bounding_box_mae: 0.2282 - bounding_box_mse: 0.0746 - classification_AUC: 0.5000 - classification_f1_score: 0.7532 - classification_loss: 0.6839 - loss: 0.0746 - val_bounding_box_iou_metric: 0.0595 - val_bounding_box_loss: 0.0742 - val_bounding_box_mae: 0.2292 - val_bounding_box_mse: 0.0743 - val_classification_AUC: 0.5000 - val_classification_f1_score: 0.8674 - val_classification_loss: 0.6745 - val_loss: 0.0743 - learning_rate: 0.0010
Epoch 5/30
107/108 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step - bounding_box_iou_metric: 0.0828 - bounding_box_loss: 0.0722 - bounding_box_mae: 0.2228 - bounding_box_mse: 0.0722 - classification_AUC: 0.4953 - classification_f1_score: 0.8215 - classification_loss: 0.6828 - loss: 0.0722
Epoch 5: val_bounding_box_mse improved from 0.07432 to 0.07106, saving model to output/checkpoints/detector_ckpt_5.keras


108/108 ━━━━━━━━━━━━━━━━━━━━ 24s 173ms/step - bounding_box_iou_metric: 0.0828 - bounding_box_loss: 0.0722 - bounding_box_mae: 0.2227 - bounding_box_mse: 0.0722 - classification_AUC: 0.4954 - classification_f1_score: 0.8206 - classification_loss: 0.6828 - loss: 0.0722 - val_bounding_box_iou_metric: 0.0757 - val_bounding_box_loss: 0.0710 - val_bounding_box_mae: 0.2222 - val_bounding_box_mse: 0.0711 - val_classification_AUC: 0.5000 - val_classification_f1_score: 0.7750 - val_classification_loss: 0.6745 - val_loss: 0.0711 - learning_rate: 0.0010
Epoch 6/30
107/108 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step - bounding_box_iou_metric: 0.0826 - bounding_box_loss: 0.0708 - bounding_box_mae: 0.2200 - bounding_box_mse: 0.0708 - classification_AUC: 0.4969 - classification_f1_score: 0.7508 - classification_loss: 0.6830 - loss: 0.0708
Epoch 6: val_bounding_box_mse did not improve from 0.07106
108/108 ━━━━━━━━━━━━━━━━━━━━ 21s 143ms/step - bounding_box_iou_metric: 0.0827 - bounding_box_loss: 0.0708 - boundin

108/108 ━━━━━━━━━━━━━━━━━━━━ 24s 173ms/step - bounding_box_iou_metric: 0.0968 - bounding_box_loss: 0.0692 - bounding_box_mae: 0.2152 - bounding_box_mse: 0.0692 - classification_AUC: 0.5000 - classification_f1_score: 0.7597 - classification_loss: 0.6847 - loss: 0.0692 - val_bounding_box_iou_metric: 0.0772 - val_bounding_box_loss: 0.0688 - val_bounding_box_mae: 0.2168 - val_bounding_box_mse: 0.0689 - val_classification_AUC: 0.5000 - val_classification_f1_score: 0.8677 - val_classification_loss: 0.6745 - val_loss: 0.0689 - learning_rate: 0.0010
Epoch 8/30
107/108 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step - bounding_box_iou_metric: 0.0986 - bounding_box_loss: 0.0680 - bounding_box_mae: 0.2128 - bounding_box_mse: 0.0680 - classification_AUC: 0.5000 - classification_f1_score: 0.7570 - classification_loss: 0.6851 - loss: 0.0680
Epoch 8: val_bounding_box_mse did not improve from 0.06890
108/108 ━━━━━━━━━━━━━━━━━━━━ 20s 138ms/step - bounding_box_iou_metric: 0.0986 - bounding_box_loss: 0.0680 - boundin

108/108 ━━━━━━━━━━━━━━━━━━━━ 21s 158ms/step - bounding_box_iou_metric: 0.1029 - bounding_box_loss: 0.0661 - bounding_box_mae: 0.2079 - bounding_box_mse: 0.0661 - classification_AUC: 0.4954 - classification_f1_score: 0.4801 - classification_loss: 0.6807 - loss: 0.0661 - val_bounding_box_iou_metric: 0.0981 - val_bounding_box_loss: 0.0653 - val_bounding_box_mae: 0.2087 - val_bounding_box_mse: 0.0654 - val_classification_AUC: 0.5000 - val_classification_f1_score: 0.2388 - val_classification_loss: 0.6745 - val_loss: 0.0654 - learning_rate: 0.0010
Epoch 11/30
107/108 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step - bounding_box_iou_metric: 0.1177 - bounding_box_loss: 0.0632 - bounding_box_mae: 0.2029 - bounding_box_mse: 0.0632 - classification_AUC: 0.4984 - classification_f1_score: 0.5180 - classification_loss: 0.6835 - loss: 0.0632
Epoch 11: val_bounding_box_mse did not improve from 0.06535
108/108 ━━━━━━━━━━━━━━━━━━━━ 20s 138ms/step - bounding_box_iou_metric: 0.1177 - bounding_box_loss: 0.0632 - bound

108/108 ━━━━━━━━━━━━━━━━━━━━ 21s 152ms/step - bounding_box_iou_metric: 0.1517 - bounding_box_loss: 0.0531 - bounding_box_mae: 0.1823 - bounding_box_mse: 0.0531 - classification_AUC: 0.4969 - classification_f1_score: 0.8572 - classification_loss: 0.6845 - loss: 0.0531 - val_bounding_box_iou_metric: 0.0961 - val_bounding_box_loss: 0.0641 - val_bounding_box_mae: 0.1997 - val_bounding_box_mse: 0.0641 - val_classification_AUC: 0.5000 - val_classification_f1_score: 0.8677 - val_classification_loss: 0.6745 - val_loss: 0.0641 - learning_rate: 1.0000e-04
Epoch 18/30
107/108 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - bounding_box_iou_metric: 0.1557 - bounding_box_loss: 0.0531 - bounding_box_mae: 0.1818 - bounding_box_mse: 0.0531 - classification_AUC: 0.4984 - classification_f1_score: 0.8635 - classification_loss: 0.6802 - loss: 0.0531
Epoch 18: val_bounding_box_mse did not improve from 0.06408
108/108 ━━━━━━━━━━━━━━━━━━━━ 18s 127ms/step - bounding_box_iou_metric: 0.1556 - bounding_box_loss: 0.0531 - b

2025/03/23 15:19:26 WARNING mlflow.models.signature: Failed to infer schema for outputs. Setting schema to `Schema([ColSpec(type=AnyType())]` as default. To see the full traceback, set logging level to DEBUG.
2025/03/23 15:19:41 WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements (model URI: /tmp/tmpt747jpkn/model, flavor: tensorflow). Fall back to return ['tensorflow==2.19.0', 'cloudpickle==3.1.1']. Set logging level to DEBUG to see the full traceback. 
2025/03/23 15:19:41 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.


1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step


2025/03/23 15:20:00 WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements (model URI: /tmp/tmp1fu0qr76/model, flavor: tensorflow). Fall back to return ['tensorflow==2.19.0', 'cloudpickle==3.1.1']. Set logging level to DEBUG to see the full traceback. 
2025/03/23 15:20:00 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.


In [26]:
raise Exception("No GPU found")

Exception: No GPU found

In [ ]:
# mlflow.tensorflow.log_model(
#     model,
#     "my_model",
#     signature=signature,
#     code_paths=["src/losses"],
# )

In [27]:
model_uri: str = "runs:/{}/model".format(run.info.run_id)
loaded_model = mlflow.tensorflow.load_model(model_uri)

loaded_model.evaluate(valid_ds, return_dict=True)

/code/.venv/lib/python3.12/site-packages/keras/src/saving/saving_lib.py:757: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 29 variables whereas the saved optimizer has 56 variables. 
  saveable.load_own_variables(weights_store.get(inner_path))


31/31 ━━━━━━━━━━━━━━━━━━━━ 12s 183ms/step - bounding_box_iou_metric: 0.0936 - bounding_box_loss: 0.0656 - bounding_box_mae: 0.2026 - bounding_box_mse: 0.0656 - classification_AUC: 0.4896 - classification_f1_score: 0.8684 - classification_loss: 0.6737 - loss: 0.0656


{'bounding_box_iou_metric': 0.09608210623264313,
 'bounding_box_loss': 0.06406838446855545,
 'bounding_box_mae': 0.19965426623821259,
 'bounding_box_mse': 0.0640789195895195,
 'classification_AUC': 0.5,
 'classification_f1_score': 0.8676717877388,
 'classification_loss': 0.6744766235351562,
 'loss': 0.0640789195895195}

## Model Evaluation

### Testing Datasets setup

In [ ]:
import matplotlib.pyplot as plt

def visualize_training_results(history):
    """
    Visualizes training and validation loss, and training and validation accuracy.

    Args:
        history: A dictionary or object containing training history data.
                 For example, a Keras History object or a dictionary with keys:
                 'loss', 'val_loss', 'accuracy', 'val_accuracy'.
    """

    if isinstance(history, dict):
        # Assumes history is a dictionary
        loss = history.get('loss')
        val_loss = history.get('val_loss')
        accuracy = history.get('accuracy')
        val_accuracy = history.get('val_accuracy')
    else:
        # Assumes history is a Keras History object or similar
        loss = history.history.get('loss')
        val_loss = history.history.get('val_loss')
        accuracy = history.history.get('accuracy')
        val_accuracy = history.history.get('val_accuracy')

    if loss and val_loss:
        epochs = range(1, len(loss) + 1)

        plt.figure(figsize=(12, 5))

        # Plot training & validation loss values
        plt.subplot(1, 2, 1)
        plt.plot(epochs, loss, 'r', label='Training loss')
        plt.plot(epochs, val_loss, 'b', label='Validation loss')
        plt.title('Training and validation loss')
        plt.xlabel('Epochs')
        plt.ylabel('Loss')
        plt.legend()

    if accuracy and val_accuracy:
        if not (loss and val_loss):
          plt.figure(figsize=(12, 5))
        else:
          plt.subplot(1, 2, 2)
        # Plot training & validation accuracy values
        plt.plot(epochs, accuracy, 'r', label='Training accuracy')
        plt.plot(epochs, val_accuracy, 'b', label='Validation accuracy')
        plt.title('Training and validation accuracy')
        plt.xlabel('Epochs')
        plt.ylabel('Accuracy')
        plt.legend()

    plt.tight_layout() #prevents overlapping titles/labels
    plt.show()


In [ ]:
visualize_training_results(history.history)

In [ ]:
prepare_test_dataset = AnnotationProcessor(annotation_file= str(TEST_DIR/'_annotations.csv'))
_class_map = {v: k for k, v in enumerate(CLASS_NAME)}
test_image_paths, test_class_ids, test_bboxes = prepare_test_dataset.process_annotations(image_dir=TEST_DIR, class_id_map=_class_map)

len(test_image_paths), len(test_class_ids), len(test_bboxes)

In [ ]:
test_dl = DataLoader(test_image_paths, test_class_ids, test_bboxes, img_size=IMG_SIZE)
test_ds = test_dl.load_val_dataset()
y_true_labels = test_dl.multi_hot_class_ids
y_true_bboxes = test_dl.padded_bbx
test_ds = Preprocessor(test_ds).preprocess()
test_ds = test_ds.batch(BATCH_SIZE)\
                .prefetch(tf.data.AUTOTUNE)

In [ ]:
results = model.evaluate(test_ds, return_dict=True, steps=1)
print("Testing accuracy: ", results)

In [ ]:
results

In [ ]:
from sklearn.metrics import classification_report

y_prob_pred, pred_bbx = model.predict(test_ds)
y_prob_pred[0], pred_bbx[0]

In [ ]:
y_pred = (y_prob_pred>0.5).astype(int)
y_pred

In [ ]:
report = classification_report(y_true_labels, y_pred, labels=[0,1,2], target_names=CLASS_NAME)
print(report)

In [ ]:
from src.utils.visualization_funcs import plot_auc_curve


plot_auc_curve(OUTPUT_DIR, CLASS_NAME, y_true_labels, y_prob_pred)

In [ ]:
test_bboxes

In [ ]:
pred_bbx

In [ ]:
from src.losses.iou_loss import iou_metric
def plot_iou_histogram(y_true_bbox, y_pred_bbox, class_ids):
    """
    Plots a histogram of Intersection over Union (IoU) scores.

    Args:
        y_true_bbox: Ground truth bounding boxes (list of lists or numpy array).
        y_pred_bbox: Predicted bounding boxes (list of lists or numpy array).
        class_ids: list of class ids.
    """
    fig, axs = plt.subplots(1)

    iou_scores = iou_metric(y_true_bbox, y_pred_bbox)

    # fig.figure(figsize=(10, 6))
    axs.hist(iou_scores, bins=20, range=(0, 1), edgecolor='black')
    axs.set_title('IoU Score Distribution')
    axs.set_xlabel('IoU Score')
    axs.set_ylabel('Frequency')
    axs.grid(True)
    plt.show()
    plt.savefig(f"{OUTPUT_DIR}/iou_histogram.png")
    return fig


In [ ]:
fig = plot_iou_histogram(y_true_bboxes, pred_bbx, pred_bbx)
mlflow.log_figure(fig, 'iou_histogram.png')